---
 - name: install mysql package
   apt: name={{ item }} state=present update_cache=yes
   with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

 - name: start mysql service
   service: name=mysql state=started enabled=yes
   
 - name: create servermail database
   mysql_db: name={{ mail_db_name }} state=present

 - name: create servermail db user
   mysql_user: name={{ mail_db_user }} password={{ mail_db_password }} priv={{ mail_db_name }}.*:ALL host='localhost' state=present
   
 - name: copy mysql db table format
   template: src=dump.sql dest=/tmp/dump.sql
   
 - name: insert table data
   shell: cat /tmp/dump.sql | mysql -u {{ mail_db_user }} -p{{ mail_db_password }} {{ mail_db_name }}
