---
 - name: Install mysql php vimbadmin postfix dovecot spamassassin roundcube nginx
   hosts: test

   roles:
     - mysql
     - php
     - vimbadmin
     - postfix
     - dovecot
     - spamassassin
     - nginx
     - roundcube
