---
 - name: Install mysql, postfix, dovecot, spamassasin
   hosts: test
   
   roles:
     - mysql
     - php
     - vimbadmin
     # - postfix
     # - dovecot
     # - spamassassin
     # - roundcube
     - nginx
 