---
 - name: git clone vimbadmin to {{ vim_path }}
   git: repo=https://github.com/opensolutions/ViMbAdmin.git dest={{ vim_path }}

 - name: download Composer
   shell: curl -sS https://getcomposer.org/installer | php

 - name: move Composer into globally-accessible location
   command: creates="/usr/local/bin/composer" mv composer.phar /usr/local/bin/composer

 - name: composer install vimbadmin
   composer: working_dir={{ vim_path }}
   environment:
    COMPOSER_PROCESS_TIMEOUT: 4000

 - name: copy application.ini files to vimbadmin folder
   template: src=application.ini dest={{ vim_path }}/application/configs/application.ini

 - name: rename .htaccess.dist to .htaccess
   command: creates="{{ vim_path }}/public/.htaccess" cp {{ vim_path }}/public/.htaccess.dist {{ vim_path }}/public/.htaccess

 - name: create the database schema
   command: ./bin/doctrine2-cli.php orm:schema-tool:create chdir={{ vim_path }}

 - name: set the ownership on the vimbadmin/var/ directory
   file: path={{ vim_path }}/var group=www-data owner=www-data state=directory recurse=yes