---
 - name: install dovecot package
   apt: name={{ item }} state=present
   with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-mysql
    
 - name: copy configuration files to dovecot folder
   template: src=dovecot.conf dest=/etc/dovecot/dovecot.conf
     
 - name: copy configuration files to dovecot folder
   template: src=dovecot-sql.conf.ext dest=/etc/dovecot/dovecot-sql.conf.ext
  
 - name: copy configuration files to dovecot/conf.d folder
   template: src=10-auth.conf dest=/etc/dovecot/conf.d/10-auth.conf

 - name: copy configuration files to dovecot/conf.d folder
   template: src=10-mail.conf dest=/etc/dovecot/conf.d/10-mail.conf

 - name: copy configuration files to dovecot/conf.d folder
   template: src=10-master.conf dest=/etc/dovecot/conf.d/10-master.conf
     
 - name: copy configuration files to dovecot/conf.d folder
   template: src=10-ssl.conf dest=/etc/dovecot/conf.d/10-ssl.conf
   
 - name: create vmail group
   group: name=vmail state=present gid=5000
   
 - name: create vmail user
   user: name=vmail group=vmail state=present uid=5000 home=/decrypted shell=/usr/sbin/nologin

 - name: create directory for each domain
   file: path=/var/mail/vhosts/{{ domain_com }} state=directory recurse=yes
   
 - name: change /var/mail ownership
   file: path=/var/mail owner=vmail group=vmail state=directory recurse=yes
   
 - name: permissions on dovecot config directory
   file: state=directory path=/etc/dovecot group=dovecot owner=vmail mode=770 recurse=yes
  notify: restart dovecot