---
 - name: install dovecot package
   apt: name={{ item }} state=present
   with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-mysql

 - name: start dovecot service
   service: name=dovecot state=started enabled=yes

 - name: create certificates directory
   file: path=/etc/dovecot/certs/ owner=dovecot group=dovecot state=directory

 - name: create cacert file
   copy: dest=/etc/dovecot/certs/mail-cacert.pem owner=dovecot group=dovecot content="/C={{ Country }}/ST={{ State }}/L={{ Locality }}/O={{ Organization }}/OU={{ OrgUnit }}/CN={{ FQDN }}"

 - name: create self-signed certificates
   command: openssl req -new -nodes -x509 -subj "/C={{ Country }}/ST={{ State }}/L={{ Locality }}/O={{ Organization }}/OU={{ OrgUnit }}/CN={{ FQDN }}" -days 3650 -keyout /etc/dovecot/certs/mail_key.pem -out /etc/dovecot/certs/mail_cert.pem -extensions v3_ca creates=/etc/dovecot/certs/mail_cert.pem

 - name: Dovecot |  Set permission for self-signed certificates
   file: path=/etc/dovecot/certs/{{ item }} state=touch owner=dovecot group=dovecot
  with_items:
    - mail_key.pem
    - mail_cert.pem

 - name: copy configuration files to dovecot folder
   template: src=dovecot.conf dest=/etc/dovecot/dovecot.conf
     
 - name: copy configuration files to dovecot folder
   template: src=dovecot-sql.conf.ext dest=/etc/dovecot/dovecot-sql.conf.ext
  
 - name: copy configuration files to dovecot/conf.d folder
   template: src=10-auth.conf dest=/etc/dovecot/conf.d/10-auth.conf

 - name: copy configuration files to dovecot/conf.d folder
   template: src=10-mail.conf dest=/etc/dovecot/conf.d/10-mail.conf

 - name: copy configuration files to dovecot/conf.d folder
   template: src=10-master.conf dest=/etc/dovecot/conf.d/10-master.conf
     
 - name: copy configuration files to dovecot/conf.d folder
   template: src=10-ssl.conf dest=/etc/dovecot/conf.d/10-ssl.conf
   
 - name: create vmail group
   group: name=vmail state=present gid=5000
   
 - name: create vmail user
   user: name=vmail group=vmail state=present uid=5000 home=/decrypted shell=/usr/sbin/nologin

 - name: create directory for each domain
   file: path=/var/mail/vhosts/{{ domain_com }} state=directory recurse=yes
   
 - name: change /var/mail ownership
   file: path=/var/mail owner=vmail group=vmail state=directory recurse=yes
   
 - name: permissions on dovecot config directory
   file: path=/etc/dovecot group=dovecot owner=vmail mode=770 state=directory recurse=yes
   notify:
    - restart dovecot