---
 - name: install dovecot package
   apt: name={{ item }} state=present
   with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-mysql
    
 - name: copy configuration files to dovecot folder
   template: src={{ item }} dest=/etc/dovecot/{{ item }}
    with_items:
     - dovecot.conf
     - dovecot-sql.conf.ext
  
 - name: copy configuration files to dovecot/conf.d folder
   template: src={{ item }} dest=/etc/dovecot/conf.d/{{ item }}
    with_items:
     - 10-auth.conf
     - 10-mail.conf
     - 10-master.conf
     - 10-ssl.conf
   notify: restart dovecot
