---
 - name: install dovecot package
   apt: name={{ item }} state=present
   with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-mysql
    
 - name: copy configuration files to dovecot folder
   template: src={{ item }} dest=/etc/dovecot/{{ item }}
    with_items:
     - dovecot.conf
     - dovecot-sql.conf.ext
  
 - name: copy configuration files to dovecot/conf.d folder
   template: src={{ item }} dest=/etc/dovecot/conf.d/{{ item }}
    with_items:
     - 10-auth.conf
     - 10-mail.conf
     - 10-master.conf
     - 10-ssl.conf
   notify: restart dovecot
   
 - name: create vmail group
   group: name=vmail state=present gid=5000
   
 - name: create vmail user
   user: name=vmail group=vmail state=present uid=5000 home=/decrypted shell=/usr/sbin/nologin
   
 - name: permissions on dovecot config directory
   file: state=directory path=/etc/dovecot group=dovecot owner=vmail mode=770 recurse=yes
  notify: restart dovecot