---
 - name: Install php package
   apt: name={{ item }} state=present
   with_items:
    - php5
    - php5-fpm
    - php5-cli
    - php5-gd
    - php5-mcrypt
    - php5-mysql
  
 - name: Start php service
   service: name=php-fpm state=started
   notify:
    - restart mysql